### ISSUE TITLE
can't display more than two columns

### ISSUE THREAD

**Issue by nomoresecrets** [GregSutcliffe/foreman_column_view#12]
Hi,

it looks like I can't display more columns than fitting in some kind of table-width-restriction

I can add two small columns(facts) like "processorcount" and "memorysize" OR one bigger like "kernelrelease". But I can't add all three of them.

Is there any solution/workaround to this?

Thanks

**Comment by GregSutcliffe** [comment]
The table is constrained by the design of the page in Foreman core, I can't modify it from a plugin easily. The only workaround I can suggest is shrinking the font (i.e zooming out) in your browser, which should display all the columns.

**Comment by nomoresecrets** [comment]
I'll try this but will probably stick to fewer columns. Thank you!
