### ISSUE TITLE
List of possible content ?

### ISSUE THREAD

**Issue by ponsfrilus** [GregSutcliffe/foreman_column_view#15]
Hi,
   I'm looking for a way to display in the host list view the "comment" field under the Additional Information tab in the host edition page.

I've tried something like `:content: facts_hash['host_comment']` or `:content: facts_hash['comment']` but none of these succeed. Does someone can tell me where can I get a list of available facts_hash, or even what's the content for the comment field ?

Thanks in advance,
ponsfrilus

EDIT: Ok now I understand that facts_hash are everything possible from facter. Any chance to get foreman content, as the comment field ? Thanks

**Comment by GregSutcliffe** [comment]
`facts_hash` refers to the list of Puppet Facts stored by Foreman for the host, so you can check the facts for possible values there. However, you can put any valid method call for a host. Simply using "comment" should work for getting the comment field.

**Comment by ponsfrilus** [comment]
Hi @GregSutcliffe,
```
    :comment:
      :title: Comment
      :after: last_report
      :content: comment
```
does the trick ! Thanks a lot !
