### ISSUE TITLE
Problem with displaying the table under foreman 1.11-develop

### ISSUE THREAD

**Issue by dgagnon** [GregSutcliffe/foreman_column_view#20]
![capture](https://cloud.githubusercontent.com/assets/1037561/10921973/9a0e2398-8246-11e5-9a01-de102f61f797.PNG)

This is the default css:

media="screen"
.table-fixed {
table-layout: fixed;
}

If I null this entry, I get this:

![capture2](https://cloud.githubusercontent.com/assets/1037561/10921989/b59524e0-8246-11e5-982b-b6ebe52dd2bf.PNG)

**Comment by dgagnon** [comment]
to fix it, I removed the table-fixed class on the main table on the host/_list.html.erb page

This is on 1.11-nighly

**Comment by tbrisker** [comment]
This should be fixed by #18

**Comment by GregSutcliffe** [comment]
thanks @tbrisker I totally forgot about that. I'll get it sorted next week.

**Comment by dgagnon** [comment]
any update on this ?

**Comment by tek0011** [comment]
according to dev:

> Foreman moved to patternfly. there's an open PR but it doesn't really improve matters, so I'm waiting on the author to help me out

**Comment by marcinbojko** [comment]
Hi guys. Is there a quick fix to resize mentioned columns?

**Comment by GregSutcliffe** [comment]
Nope. The Patternfly columns don't like this plugin, and I can't fix it. I'm hoping @tbrisker will be able to come up with a solution, but he's super busy right now :/

**Comment by marcinbojko** [comment]
Thanks Greg. We will have to get used to it :(

**Comment by mgriffin13** [comment]
Just a +1, as we are working to upgrade from Foreman 1.10 to 1.12 and used foreman_column_view for 3 different columns, none of which display properly in 1.12.

**Comment by dimatha** [comment]
+1 used to use this plugin a lot !

**Comment by tbrisker** [comment]
https://github.com/theforeman/foreman/pull/3884 along with #18 should fix these issues.

**Comment by dgoetz** [comment]
Can confirm that it is working again. :+1: 
@GregSutcliffe: Bug can be closed! :smile:

**Comment by GregSutcliffe** [comment]
Thx @dgoetz totally forgot to close this :P
