### ISSUE TITLE
uses alias_method_chain, probably incompatible with foreman 1.17

### ISSUE THREAD

**Issue by Zugschlus** [GregSutcliffe/foreman_column_view#30]
Hi,

foreman 1.17 ships with rails 5, which does not have alias_method_chain any more. This makes it likely that the plugin won't run any more with foreman 1.17 (haven't tried it yet).

Sorry, my RoR knowledge is not enough to submit a patch.

Greetings
Marc

**Comment by GregSutcliffe** [comment]
Thanks for the patience @Zugschlus - I've been out of action for a while. #31 should fix it once merged.

**Comment by GregSutcliffe** [comment]
Fixed in #31, thanks @Zugschlus

**Comment by GregSutcliffe** [comment]
0.4.0 is now in the pacakge repos, thanks again for the patience
